# Generated by Django 5.2.1 on 2025-06-25 11:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0008_alter_comment_parent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newspost",
            old_name="creator",
            new_name="user",
        ),
    ]
