# Generated by Django 5.2.1 on 2025-06-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stocknewsurlrule",
            old_name="click_button",
            new_name="news",
        ),
        migrations.RemoveField(
            model_name="stocknewsurlrule",
            name="div_list",
        ),
        migrations.RemoveField(
            model_name="stocknewsurlrule",
            name="tbody",
        ),
        migrations.AddField(
            model_name="stocknewsurlrule",
            name="search_bar",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
