# Generated by Django 5.2.1 on 2025-06-23 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_stocknewsurlrule_main_div_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsurlrule',
            name='url',
        ),
        migrations.DeleteModel(
            name='NewsURL',
        ),
        migrations.DeleteModel(
            name='NewsURLRule',
        ),
    ]
